spring : 
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projetjee?serverTimezone=UTC
    username: root
    password: elhadj032019
    platform: mysql
  jpa:
     hibernate:
       ddl-auto: create-drop
     generate-ddl: true
     show-sql: true
     properties:
                   hibernate:
                             dialect: "org.hibernate.dialect.MySQL5Dialect"
  
  
  profiles:
      active:
        - "dev"         
        
  


server:
  port: 8080
  
  error:
    whitelabel:
       enabled: false
  